let adminData={clients:[],orders:[],messages:[]};
const views=document.querySelectorAll('.view'),navItems=document.querySelectorAll('.nav-item'),pageTitle=document.getElementById('pageTitle');
const colors={'Novo':['#DBEAFE','#1D4ED8'],'Em análise':['#FEF3C7','#B45309'],'Em produção':['#EDE9FE','#6D28D9'],'Revisão':['#FCE7F3','#BE185D'],'Entregue':['#DCFCE7','#15803D'],'Concluído':['#E2E8F0','#334155']};
const prog={'Novo':10,'Em análise':30,'Em produção':70,'Revisão':90,'Entregue':95,'Concluído':100};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const badge=s=>{const c=colors[s]||colors['Concluído'];return `<span class="badge" style="background:${c[0]};color:${c[1]}">${esc(s)}</span>`};
const client=id=>adminData.clients.find(c=>c.id===id)||{};
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===id));const i=[...navItems].find(n=>n.dataset.view===id);pageTitle.textContent=i?i.innerText.trim():'Dashboard';document.getElementById('sidebar').classList.remove('open')}
navItems.forEach(i=>i.onclick=()=>showView(i.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));document.getElementById('mobileToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
function renderDashboard(){const o=adminData.orders;document.getElementById('statNew').textContent=o.filter(x=>x.status==='Novo').length;document.getElementById('statProgress').textContent=o.filter(x=>x.status==='Em produção').length;document.getElementById('statClients').textContent=adminData.clients.length;document.getElementById('statValue').textContent=o.reduce((s,x)=>s+Number(x.value_eur||0),0).toLocaleString('pt-PT')+'€';
document.getElementById('recentOrders').innerHTML=o.slice(0,4).map(x=>{const c=client(x.client_id);return `<div class="order-row"><div><h3>${esc(x.order_number)} · ${esc(c.full_name||'Cliente')}</h3><p>${esc(c.company_name||'')} · ${esc(x.service_name)} · ${Number(x.value_eur||0)}€</p></div>${badge(x.status)}</div>`}).join('');
const states=Object.keys(colors),mx=Math.max(1,...states.map(s=>o.filter(x=>x.status===s).length));document.getElementById('statusSummary').innerHTML=states.map(s=>{const n=o.filter(x=>x.status===s).length;return `<div class="summary-row"><span>${s}</span><div class="bar"><i style="width:${n/mx*100}%"></i></div><strong>${n}</strong></div>`}).join('')}
function renderOrders(){const q=document.getElementById('orderSearch').value.toLowerCase(),f=document.getElementById('statusFilter').value;const list=adminData.orders.filter(o=>{const c=client(o.client_id),h=`${o.order_number} ${c.full_name||''} ${c.company_name||''}`.toLowerCase();return(!f||o.status===f)&&h.includes(q)});document.getElementById('ordersTable').innerHTML=list.map(o=>{const c=client(o.client_id);return `<tr><td><strong>${esc(o.order_number)}</strong></td><td>${esc(c.full_name||'Cliente')}<br><small>${esc(c.company_name||'')}</small></td><td>${esc(o.service_name)}</td><td>${Number(o.value_eur||0)}€</td><td>${badge(o.status)}</td><td><button class="table-action" onclick="advanceStatus('${o.id}')">Avançar estado</button></td></tr>`}).join('')||'<tr><td colspan="6">Nenhum pedido encontrado.</td></tr>'}
window.advanceStatus=async id=>{const flow=['Novo','Em análise','Em produção','Revisão','Entregue','Concluído'],o=adminData.orders.find(x=>x.id===id),n=flow[Math.min(Math.max(0,flow.indexOf(o.status))+1,flow.length-1)];await adminUpdateOrder(id,{status:n,progress:prog[n]});await load()};
function renderClients(){document.getElementById('clientsGrid').innerHTML=adminData.clients.map(c=>{const o=adminData.orders.filter(x=>x.client_id===c.id),t=o.reduce((s,x)=>s+Number(x.value_eur||0),0);return `<article class="client-card"><h3>${esc(c.full_name)}</h3><p>${esc(c.company_name||'')}</p><p>${esc(c.email||c.phone||'')}</p><p><strong>${o.length}</strong> pedido(s) · <strong>${t}€</strong></p></article>`}).join('')}
function renderMessages(){const x=document.getElementById('adminMessages');x.innerHTML=adminData.messages.map(m=>{const c=client(m.client_id);return `<article class="admin-message ${m.is_read?'':'unread'}"><div><strong>${esc(c.full_name||'Cliente')}</strong><small>${new Date(m.created_at).toLocaleString('pt-PT')}</small></div><p>${esc(m.body)}</p>${m.is_read?'<span>Lida</span>':`<button onclick="markMessageRead('${m.id}')">Marcar como lida</button>`}</article>`}).join('')||'<p>Sem mensagens.</p>'}
window.markMessageRead=async id=>{await adminMarkMessageRead(id);await load()};
function selectClients(){const s=document.querySelector('#orderForm [name="client_id"]');s.innerHTML=adminData.clients.map(c=>`<option value="${c.id}">${esc(c.full_name)} — ${esc(c.company_name||'')}</option>`).join('')}
function render(){renderDashboard();renderOrders();renderClients();renderMessages();selectClients()}
async function load(){adminData=await adminFetchData();render()}
document.getElementById('orderSearch').oninput=renderOrders;document.getElementById('statusFilter').onchange=renderOrders;
const dialog=document.getElementById('orderDialog');document.getElementById('newOrderButton').onclick=()=>dialog.showModal();
document.getElementById('orderForm').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target),s=d.get('status');await adminCreateOrder({client_id:d.get('client_id'),service_name:d.get('service'),value_eur:Number(d.get('value')),status:s,progress:prog[s],priority:'Normal'});e.target.reset();dialog.close();await load()};
document.getElementById('adminLogout').onclick=adminLogout;
(async()=>{const p=await requireAdmin();if(!p)return;document.getElementById('adminName').textContent=p.full_name||'Administrador';if(aiOfficeSupabase){document.getElementById('adminModeLabel').textContent='Ligado ao Supabase';document.getElementById('adminModeText').textContent='Dados carregados da base de dados.'}await load()})();