const db=window.supabaseClient||window.aiOfficeSupabase||null;let customerId=null,contacts=[],selected=null;const list=document.getElementById('contactList'),panel=document.getElementById('contactPanel'),dialog=document.getElementById('contactDialog'),form=document.getElementById('contactForm');
async function init(){if(!db)return;const{data:{session}}=await db.auth.getSession();if(!session){location.href='login.html?redirect=crm.html';return}const{data}=await db.from('customers').select('id').eq('auth_user_id',session.user.id).maybeSingle();if(!data)return;customerId=data.id;load()}
async function load(){const{data,error}=await db.from('crm_contacts').select('*').eq('customer_id',customerId).order('updated_at',{ascending:false});if(error){list.innerHTML='<p>Erro ao carregar CRM.</p>';return}contacts=data||[];render();stats()}
function shown(){const q=document.getElementById('search').value.toLowerCase(),s=document.getElementById('statusFilter').value;return contacts.filter(c=>(!q||[c.full_name,c.company,c.email].filter(Boolean).join(' ').toLowerCase().includes(q))&&(!s||c.status===s))}
function render(){const rows=shown();list.innerHTML=rows.length?'':'<p style="padding:20px">Ainda não existem contactos.</p>';rows.forEach(c=>{const r=document.createElement('div');r.className='contact-row';r.innerHTML=`<div><strong>${esc(c.full_name)}</strong><small>${esc(c.company||'Sem empresa')}</small></div><div><small>${esc(c.email||'Sem email')}</small></div><div><span class="badge">${label(c.status)}</span></div><div><strong>${money(c.estimated_value)}</strong></div>`;r.onclick=()=>select(c);list.appendChild(r)})}
function stats(){document.getElementById('statTotal').textContent=contacts.length;document.getElementById('statLeads').textContent=contacts.filter(c=>c.status==='lead').length;document.getElementById('statClients').textContent=contacts.filter(c=>c.status==='cliente').length;document.getElementById('statValue').textContent=money(contacts.reduce((a,c)=>a+Number(c.estimated_value||0),0))}
function select(c){selected=c;panel.innerHTML=`<h2>${esc(c.full_name)}</h2><span class="badge">${label(c.status)}</span><div class="detail-grid"><div><span>Empresa</span><strong>${esc(c.company||'—')}</strong></div><div><span>Email</span><strong>${esc(c.email||'—')}</strong></div><div><span>Telefone</span><strong>${esc(c.phone||'—')}</strong></div><div><span>Valor</span><strong>${money(c.estimated_value)}</strong></div><div><span>Próxima ação</span><strong>${esc(c.next_action||'—')}</strong></div><div><span>Notas</span><strong>${esc(c.notes||'—')}</strong></div></div><div class="panel-actions"><button onclick="editSelected()">Editar</button><button onclick="askAI('followup')">Criar follow-up</button><button onclick="askAI('summary')">Resumo IA</button><button onclick="deleteSelected()">Eliminar</button></div>`}
function openDialog(c=null){document.getElementById('dialogTitle').textContent=c?'Editar contacto':'Novo contacto';for(const [id,key] of [['contactId','id'],['fullName','full_name'],['company','company'],['email','email'],['phone','phone'],['role','role'],['source','source'],['estimatedValue','estimated_value'],['nextAction','next_action'],['notes','notes']])document.getElementById(id).value=c?.[key]||'';document.getElementById('status').value=c?.status||'lead';document.getElementById('nextActionAt').value=c?.next_action_at?c.next_action_at.slice(0,16):'';dialog.showModal()}
form.onsubmit=async e=>{e.preventDefault();const id=document.getElementById('contactId').value,p={customer_id:customerId,full_name:document.getElementById('fullName').value.trim(),company:val('company'),email:val('email'),phone:val('phone'),role:val('role'),source:val('source'),status:document.getElementById('status').value,estimated_value:Number(document.getElementById('estimatedValue').value||0),next_action:val('nextAction'),next_action_at:document.getElementById('nextActionAt').value||null,notes:val('notes'),updated_at:new Date().toISOString()};const{error}=id?await db.from('crm_contacts').update(p).eq('id',id).eq('customer_id',customerId):await db.from('crm_contacts').insert(p);if(error){alert(error.message);return}dialog.close();load()}
window.editSelected=()=>selected&&openDialog(selected);window.deleteSelected=async()=>{if(!selected||!confirm('Eliminar este contacto?'))return;await db.from('crm_contacts').delete().eq('id',selected.id).eq('customer_id',customerId);selected=null;panel.innerHTML='<p>Selecione um contacto.</p>';load()};window.askAI=mode=>{if(!selected)return;const ctx=`Contacto: ${selected.full_name}
Empresa: ${selected.company||'—'}
Estado: ${label(selected.status)}
Valor estimado: ${money(selected.estimated_value)}
Notas: ${selected.notes||'—'}
Próxima ação: ${selected.next_action||'—'}`;localStorage.setItem('aiOfficePendingPrompt',mode==='followup'?`Escreve uma mensagem profissional de acompanhamento comercial.

${ctx}`:`Cria um resumo comercial e recomenda os próximos passos.

${ctx}`);location.href='intelligence.html'};
document.getElementById('newContact').onclick=()=>openDialog();document.getElementById('cancelDialog').onclick=()=>dialog.close();document.getElementById('search').oninput=render;document.getElementById('statusFilter').onchange=render;document.getElementById('aiSummary').onclick=()=>{const s=shown().slice(0,25).map(c=>`${c.full_name} | ${label(c.status)} | ${money(c.estimated_value)} | ${c.next_action||'sem próxima ação'}`).join('
');localStorage.setItem('aiOfficePendingPrompt',`Analisa estes contactos. Identifica prioridades, riscos e próximas ações.

${s}`);location.href='intelligence.html'};
function val(id){return document.getElementById(id).value.trim()||null}function label(s){return({lead:'Lead',contactado:'Contactado',proposta:'Proposta enviada',negociacao:'Negociação',cliente:'Cliente',perdido:'Perdido'})[s]||s}function money(v){return new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(v||0))}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}init();