const db=window.supabaseClient||window.aiOfficeSupabase||null;let customerId=null,tasks=[],contacts=[];const $=id=>document.getElementById(id);const els={list:$('taskList'),agenda:$('agendaList'),dialog:$('taskDialog'),form:$('taskForm'),search:$('search'),status:$('statusFilter'),priority:$('priorityFilter')};
async function init(){if(!db){alert('Supabase não configurado em js/config.js.');return}const{data:{session}}=await db.auth.getSession();if(!session){location.href='login.html?redirect=tasks.html';return}const{data,error}=await db.from('customers').select('id').eq('auth_user_id',session.user.id).maybeSingle();if(error||!data){els.list.innerHTML='<p class="empty">Perfil de cliente não encontrado.</p>';return}customerId=data.id;await loadContacts();await loadTasks()}
async function loadContacts(){const{data}=await db.from('crm_contacts').select('id,full_name,company').eq('customer_id',customerId).order('full_name');contacts=data||[];const s=$('contactId');s.innerHTML='<option value="">Sem contacto</option>';contacts.forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=`${c.full_name}${c.company?` — ${c.company}`:''}`;s.appendChild(o)})}
async function loadTasks(){const{data,error}=await db.from('crm_tasks').select('*,crm_contacts(full_name,company)').eq('customer_id',customerId).order('due_at',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(error){els.list.innerHTML='<p class="empty">Não foi possível carregar as tarefas.</p>';return}tasks=data||[];render();agenda();stats()}
function shown(){const q=els.search.value.trim().toLowerCase(),s=els.status.value,p=els.priority.value;return tasks.filter(t=>{const h=[t.title,t.description,t.crm_contacts?.full_name].filter(Boolean).join(' ').toLowerCase();return(!q||h.includes(q))&&(!s||t.status===s)&&(!p||t.priority===p)})}
function render(){const rows=shown();if(!rows.length){els.list.innerHTML='<p class="empty">Ainda não existem tarefas.</p>';return}els.list.innerHTML='';rows.forEach(t=>{const r=document.createElement('article');r.className=`task-item ${t.status==='done'?'done':''}`;r.innerHTML=`<input class="task-check" type="checkbox" ${t.status==='done'?'checked':''}><div class="task-main"><strong>${esc(t.title)}</strong><small>${esc(t.description||'Sem descrição')}</small><small>${t.crm_contacts?.full_name?`Contacto: ${esc(t.crm_contacts.full_name)}`:'Sem contacto associado'}</small></div><div class="task-meta"><span class="badge ${t.priority}">${prio(t.priority)}</span><small>${date(t.due_at)}</small><div class="task-actions"><button data-a="edit">Editar</button><button data-a="delete">Eliminar</button></div></div>`;r.querySelector('.task-check').onchange=()=>toggle(t);r.querySelector('[data-a="edit"]').onclick=()=>openDialog(t);r.querySelector('[data-a="delete"]').onclick=()=>remove(t);els.list.appendChild(r)})}
function agenda(){const now=new Date(),end=new Date();end.setDate(end.getDate()+7);const up=tasks.filter(t=>t.status!=='done'&&t.due_at&&new Date(t.due_at)>=new Date(now.getFullYear(),now.getMonth(),now.getDate())&&new Date(t.due_at)<end);if(!up.length){els.agenda.innerHTML='<p class="empty">Sem compromissos nos próximos 7 dias.</p>';return}const g={};up.forEach(t=>{const k=new Date(t.due_at).toISOString().slice(0,10);(g[k]||=[]).push(t)});els.agenda.innerHTML='';Object.keys(g).sort().forEach(k=>{const s=document.createElement('section');s.className='agenda-day';const d=new Date(`${k}T12:00:00`);s.innerHTML=`<h3>${d.toLocaleDateString('pt-PT',{weekday:'long',day:'2-digit',month:'long'})}</h3>`;g[k].forEach(t=>{const i=document.createElement('div');i.className='agenda-entry';i.innerHTML=`<strong>${esc(t.title)}</strong><small>${new Date(t.due_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small>`;s.appendChild(i)});els.agenda.appendChild(s)})}
function stats(){const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(a);b.setDate(b.getDate()+1);$('statPending').textContent=tasks.filter(t=>t.status==='pending').length;$('statDone').textContent=tasks.filter(t=>t.status==='done').length;$('statToday').textContent=tasks.filter(t=>t.due_at&&t.status!=='done'&&new Date(t.due_at)>=a&&new Date(t.due_at)<b).length;$('statLate').textContent=tasks.filter(t=>t.due_at&&t.status!=='done'&&new Date(t.due_at)<a).length}
function openDialog(t=null){$('dialogTitle').textContent=t?'Editar tarefa':'Nova tarefa';$('taskId').value=t?.id||'';$('title').value=t?.title||'';$('description').value=t?.description||'';$('priority').value=t?.priority||'normal';$('status').value=t?.status||'pending';$('dueAt').value=t?.due_at?t.due_at.slice(0,16):'';$('contactId').value=t?.contact_id||'';els.dialog.showModal()}
els.form.onsubmit=async e=>{e.preventDefault();const id=$('taskId').value,s=$('status').value,p={customer_id:customerId,contact_id:$('contactId').value||null,title:$('title').value.trim(),description:$('description').value.trim()||null,priority:$('priority').value,status:s,due_at:$('dueAt').value||null,completed_at:s==='done'?new Date().toISOString():null,updated_at:new Date().toISOString()};const q=id?db.from('crm_tasks').update(p).eq('id',id).eq('customer_id',customerId):db.from('crm_tasks').insert(p);const{error}=await q;if(error){alert(error.message);return}els.dialog.close();await loadTasks()};
async function toggle(t){const done=t.status!=='done';const{error}=await db.from('crm_tasks').update({status:done?'done':'pending',completed_at:done?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',t.id).eq('customer_id',customerId);if(error)alert(error.message);else await loadTasks()}
async function remove(t){if(!confirm('Eliminar esta tarefa?'))return;const{error}=await db.from('crm_tasks').delete().eq('id',t.id).eq('customer_id',customerId);if(error)alert(error.message);else await loadTasks()}
$('newTask').onclick=()=>openDialog();$('cancelDialog').onclick=()=>els.dialog.close();els.search.oninput=render;els.status.onchange=render;els.priority.onchange=render;$('aiPlan').onclick=()=>{const p=tasks.filter(t=>t.status==='pending').slice(0,30).map(t=>`${t.title} | prioridade ${prio(t.priority)} | prazo ${date(t.due_at)} | contacto ${t.crm_contacts?.full_name||'sem contacto'}`).join('\n');localStorage.setItem('aiOfficePendingPrompt',`Organiza estas tarefas por prioridade e cria um plano de execução para hoje e para os próximos dias.\n\n${p||'Não existem tarefas pendentes.'}`);location.href='intelligence.html'};
function prio(v){return({high:'Alta',normal:'Normal',low:'Baixa'})[v]||v}function date(v){return v?new Date(v).toLocaleString('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'Sem data'}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}init();
